### ISSUE TITLE
Offline breadcrumb documentation explaining where the supporting code is

### ISSUE THREAD

**Issue by paulio** [microsoft/TemplateStudio#2004]
One of the goals of the template studio template(s) seems to be to provide the recommended approach in how to implement certain common features. It's very good at that. However, whilst there are links in the code to the supporting documentation what it's not so good at is explaining how all the bits of the puzzle join up, especially if you are adding features in the future rather than using the template - i.e. the template can be a tool for teaching as well as producing. For example, you create application 1 with background task support, and application 2 without. Later on you decide to add background task support to app 2. You look at app 1 and see the main code generated code classes. One argument (A)would be that at that point the developer will follow the links in that code and learn what it takes to implement a background task. Another argument (B) is that the developer will copy and paste the code without spending the effort to learn about implementing background tasks, because the documentation isn't great (partly why a template like this exists in the first place). The problem with B's approach is that the code to create and maintain a background task is actually tucked away in a number of areas. E.g. App.xaml.cs. 

What I am suggesting is that in the production of this template there is an amount of knowledge/expertise that is above the online documentation. This could be imparted to the developer via a story/breadcrumb/explanation-log into the produced code. E.g. (basic example) 

Adding Background Task Support for BackgroundTaskMyApp
1. Added abstract task class to support any background task 
2. Added concrete task class to support the specific BackgroundTaskMyApp - put your specific code here
3. Added code to Activation Class - supports registering the background task, requesting access
4. Added code to App.xaml.cs - supports handling the invocation of the background task

The above examples could also contain links, further explanations, etc. and would be in a text document for future reviewing.

**Comment by mrlacey** [comment]
@paulio Did you know that you can add to a project once it's been created? Right-click on the project and select 'Add Page' or 'Add Feature'.
Your scenario about creating another project with a new feature and copying the changes over seems completely redundant and not how we'd recommend doing it.

![image](https://user-images.githubusercontent.com/189547/36787278-7ccca4a8-1c81-11e8-9037-d4d16840cc66.png)

The second step in the wizard is then a summary of all the changes, additions, etc. that are made to the project.

![image](https://user-images.githubusercontent.com/189547/36787335-bad89d7e-1c81-11e8-8c7b-3c590e33921c.png)

Then, when the page/feature is added, WTS displays a document that summarizes all the changes.
Here's an example (with slight formatting tweaking for display here.)

```
# Generation summary
The following changes have been incorporated into your project:

You can find the files from the generation in the temporary generation folder: C:\Users\matt\AppData\Local\Temp\WTSTempGeneration\99bd2b03-18b5-4685-9e43-c66b51becda0\App62_20180228_121929

## New files:
These files have been added to your project.
* [BackgroundTasks\BackgroundTask.cs](about:/C:/Users/matt/Source/repos/App62/App62/BackgroundTasks/BackgroundTask.cs)
* [BackgroundTasks\BackgroundTask1.cs](about:/C:/Users/matt/Source/repos/App62/App62/BackgroundTasks/BackgroundTask1.cs)
* [Helpers\TaskExtensions.cs](about:/C:/Users/matt/Source/repos/App62/App62/Helpers/TaskExtensions.cs)
* [Services\BackgroundTaskService.cs](about:/C:/Users/matt/Source/repos/App62/App62/Services/BackgroundTaskService.cs)

## Modified files:
The following changes have been applied:

### Changes in file 'Services\ActivationService.cs':
See the final result: [Services\ActivationService.cs](about:/C:/Users/matt/Source/repos/App62/App62/Services/ActivationService.cs)

 ``CSHARP
//***
// These code blocks include the BackgroundTaskService Instance in the method `GetActivationHandlers()`
// and background task registration to the method `InitializeAsync()` in the ActivationService of your project.
//***

using System;
//Block to be included
using App62.Helpers;
//End of block

namespace App62.Services
{
    internal class ActivationService
    {
        private async Task InitializeAsync()
        {
            //Block to be included
            Singleton<BackgroundTaskService>.Instance.RegisterBackgroundTasks();
            //End of block
        }

        private IEnumerable<ActivationHandler> GetActivationHandlers()
        {
            //Block to be included
            yield return Singleton<BackgroundTaskService>.Instance;
            //End of block
        }
    }
}

 ``


### Changes in file 'Services\BackgroundTaskService.cs':
See the final result: [Services\BackgroundTaskService.cs](about:/C:/Users/matt/Source/repos/App62/App62/Services/BackgroundTaskService.cs)

 ``CSHARP
//***
// This code block adds the BackgroundTask1 to the method `CreateInstances()` of the BackgroundTaskService of your project.
//***
namespace App62.Services
{
    internal class BackgroundTaskService : ActivationHandler<BackgroundActivatedEventArgs>
    {
        private static IEnumerable<BackgroundTask> CreateInstances()
        {
            var backgroundTasks = new List<BackgroundTask>();
//Include the following block at the end of the containing block.
//Block to be included
            backgroundTasks.Add(new BackgroundTask1());
//End of block
            return backgroundTasks;
        }
    }
}

``
 ``CSHARP
//***
// This code block adds the BackgroundTask1 to the method `CreateInstances()` of the BackgroundTaskService of your project.
//***
namespace App62.Services
{
    internal class BackgroundTaskService : ActivationHandler<BackgroundActivatedEventArgs>
    {
        private static IEnumerable<BackgroundTask> CreateInstances()
        {
            var backgroundTasks = new List<BackgroundTask>();
//Include the following block at the end of the containing block.
//Block to be included
            backgroundTasks.Add(new BackgroundTask1());
//End of block
            return backgroundTasks;
        }
    }
}

``


### Changes in file 'App.xaml.cs':
See the final result: [App.xaml.cs](about:/C:/Users/matt/Source/repos/App62/App62/App.xaml.cs)

 ``CSHARP
//***
// This code block adds the OnBackgroundActivated event handler to the App class of your project.
//***
namespace App62
{
    public sealed partial class App : Application
    {
//Include the following block at the end of the containing block.
//Block to be included

        protected override async void OnBackgroundActivated(BackgroundActivatedEventArgs args)
        {
            await ActivationService.ActivateAsync(args);
        }
//End of block
    }
}

``

```

This looks equivalent to your list of changes.

If you want, you can even have the wizard generate a copy of the project with the changes in so you can manually compare the differences later. (Check box option in the bottom right of the window.)


I'm not sure what your proposal adds beyond a few more links to documentation.

**Comment by paulio** [comment]
No I didn't know about the additional menu item, that's great. The generated documentation is good and covers what I suggested with a couple of exceptions. The document is generated into temp (I'd prefer it with the project) and I can't see the documentation from the original run. If those two things where in place then I would cover the 'teaching' aspect of this issue.

**Comment by mrlacey** [comment]
The documentation is in a temp folder as it's with copies of all the changed files. There could be a lot of these (especially if adding multiple items) and we don't want to clutter a repository with a lot of files that few people will ever need. Having the summary doc in a separate location to the copied files could easily lead to one being deleted without the other and severly impacting the usefulness of each.
If you wanted to keep a copy of this documentation you could always move it somewhere else.

Documentation isn't created as part of the initial project generation. That's why you can't see it.


In terms of the teaching aspect. That's not what WTS is for. It does not exist to teach anyone how to build an app or how the underlying fundamentals of UWP apps and the app model.
I strongly believe that if you're going to build an app for a platform you really should learn about that platform before you write (or generate) any code.
WTS will not build a whole app. It is intentionally just a starting point. Anyone using this should understand that or they'll be setting themselves up for disappointment.

Focusing again on Background Tasks.
- Before adding one to an app you should know about what they're good for. Plus any limitations or restrictions.
- You should have a basic understanding of how they work from an API perspective and how they can interact with the main app.

Without this knowledge, you won't know if it's right to include one in your app anyway.
If you've got to know this first, then any documentation we provided would be a duplication.
We assume some level of basic knowledge and ability to work out how things work together or we'd need to include large amounts of comments in the generated code and (hopefully) for most people this would be noise and clutter.

If you wanted to see what gets modified in a project for every page or feature option, you could use the right-click/Add functionality to generate explanations for all the changes each includes. (Beware that there is some variation depending on the combination of programming language, project type, and framework selected.)

If using WTS to create an app, I'd advise against creating what will be the final project straight away. Start with multiple experimental projects that each include only one or two features that you think you might need. This way you can look at what they contain in relative isolation and assess how useful and relevant they are to your specific needs. When you know what you want, you can create the project that contains all the pages and features you need.

I really don't like the idea that someone would say "I've generated an app with many features. Now explain how they all work."
Learning how multiple things work at the same time is much harder than learning about separate things individually.
More importantly, it's necessary to know about the platform and the items included when the app was generated before you include them in an app.

There's also the issue of maintaining an additional set of documentation. Including additional documentation would be an extra overhead to create and maintain. This would mean fewer features being added and bugs fixed in the future.

**Comment by joshkore** [comment]
I really need a sample of how to start up a task.  I know where to insert my code but can't find any documentation on how to get a task running.  I assume I have to use the BackgroundTaskservice class somehow?

**Comment by joshkore** [comment]
What is the name of the temp folder where the documentation is located for background tasks?

**Comment by crutkas** [comment]
Template studio is a hybrid of todo’s / code comments / links off to the official docs.microsoft.com site in the actual generated code.   We don’t gen offline docs.

**Comment by joshkore** [comment]
I did a search on GitHub for the BackgroundTaskService code and found a million matches of people generating projects using the WTS and not a single project actually activated one of the background tasks.  And these are all people who select background tasks in the wizard.  Some of them even named their background task but still never used it.  I suspect nobody knows how.

**Comment by mikebattista** [comment]
I believe https://docs.microsoft.com/en-us/windows/uwp/launch-resume/debug-a-background-task covers how to debug in-proc and out-of-proc background tasks.
