### ISSUE TITLE
WinUI 3 C# UWP Templates

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/TemplateStudio#4012]
# WinUI 3 C# UWP Templates

## Summary
WinTS currently offers a way to create a WinUI 3 Desktop app in C# via the wizard with some limitations compared to the other templates. The team will continue to expand on this effort by reaching the right level of parity with WinUI 3 UWP templates written in C#. 

## Rationale

* WinUI 3 will cover the whole native Windows UI platform. Ranging from Win32 to UWP, it will enable developers to create apps with a modern UX framework.
* WinTS currently has no templating support for WinUI 3 UWP in C#.
* WinTS will be able to provide a better File -> New Project experience than the one currently offered for WinUI 3 UWP apps.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Provide an easy way for users to create a WinUI 3 C# UWP app through template studio | Must |
| Provide users with a blank template as a starting point | Must |
| Have documentation for using these templates | Must |
| Identify issues with WinUI 3 during the dev process and document them on the WinUI repo | Should |
| Expand in the future to include more common templates in our wizard like the ones offered already for WinUI 3 Desktop in C# | Should |

## Roadmap
Roadmap is still being defined and will be updated in the future as we explore different options.

**Comment by mvegaca** [comment]
Working on that in [this](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue4012-WinUI3UWP) WinTS branch and [this](https://github.com/mvegaca/CoreTemplateStudio/tree/Issue4012-WinUI3UWPCore) CoreTS branch.

**Comment by mrlacey** [comment]
This issue is very vague. It feels more like a project or epic.
Are there more details about what is being implemented? 
Is it all the options that are currently available for UWP apps? If not all, which and why?

Keeping this as a single, all-encompassing issue can easily lead:
- to lots of discussions getting lost in a long thread.
- an issue that is open for a very long time and hides progress that is being made.
- discussions and decisions relating to individual components that are implemented either being lost or not documented because they don't apply to the issue as a whole.

I expect the different pages/features/services/etc. to be tracked with different issues to enable the monitoring of progress and to avoid everything going in one MASSIVE PR.

If this is just about exploring options and what works or is currently available, I would expect this to produce documentation. At the moment, it seems the only artifacts are a couple of branches created 6 weeks ago.

**Comment by sibille** [comment]
We're still exploring what we want to generate here, as we found some blocking issues, like behaviours or WCT toolkit not supporting WinUI3 UWP yet. We'll update the issue once we have that figured out. 

The branches mentioned above are outdated. We'll create a mockup first, then templates, I'll hide the comment to avoid confusion.

**Comment by sibille** [comment]
The mockup can be found at: https://github.com/microsoft/WindowsTemplateStudio/tree/Mockup-WinUI3CsUwp, but needs an update to Project Reunion 0.5

**Comment by mikebattista** [comment]
This is no longer a priority given the latest priorities of WinUI 3 and the Windows App SDK.

See https://github.com/microsoft/TemplateStudio/blob/dev/docs/roadmap.md for our latest roadmap.
