### ISSUE TITLE
.NET 6 support for WPF templates

### ISSUE THREAD

**Issue by Luk164** [microsoft/TemplateStudio#4020]
**Describe the solution you'd like**
Templates for using .NET 5 with WPF/UWP/WinUI. Also consider switching core project to 5.0, since there is no longer any reason to keep it on .NET Standart I believe.

**Describe alternatives you've considered**
A switch that can be toggled to select either 3.0 or 5.0, but that seems counterproductive in the long run.

**Additional context**
I know there was already some discourse about WinUI, but I did not see the other two mentioned anywhere.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No  |  Yes  | No |

**Comment by mrlacey** [comment]
> Also consider switching core project to 5.0, since there is no longer any reason to keep it on .NET Standart I believe.

The purpose of the "Core" project is to contain logic that can be used elsewhere beyond the app. Having this target .NET5 may limit that use. Having it remain a .NET Standard library should enable the wider range of projects that can reference it. Unless there's a good reason to change it it should remain a standard library.
There is, of course, no reason to stop anyone wanting to change the generated library to target .NET5 (or both) if they wish.

**Comment by mrlacey** [comment]
There are two big blockers to changing the current WPF templates to target .NET5.

- WebView(2)
- XAML Islands

The `WebView` control is deprecated in .NET5 and it's replacement (`Webview2`) is still in preview.
Windows Template Studio has always avoided generating apps that include controls or libraries that are still in preview because of the risk to breaking changes being introduced before the referenced item leaves preview.
Updating to target .NET5 would mean breaking this policy for preview functionality or removing the WebView option.

XAML Islands are only supported in projects that target .NET Core 3.1.
Updating to target .NET5 would mean removing the XAML Island option.
XAML Islands use Windows 10 UI technologies (`Windows.UI.XAML`) but there is not yet a version of this that support targeting .NET5. It is expected that support for this will come with WinUI3. The current WinUI3 previews do not work with WPF due to issues with support for ARM targeting (WPF doesn't have it and WinUI assumes it will be there.)


As far as I can tell, it's not going to be possible to update the WPF templates to target .NET5 until WebView2 and WinUI3 are out of preview.
According to the [latest roadmap](#4013) this work isn't likely to begin until June 2021 which ties in with the WinUI3 release coming in the "first half of 2021" so set expectations accordingly.

**Comment by Luk164** [comment]
@mrlacey Would it be possible to add a selection box and disable the two problematic options when choosing .NET5?

**Comment by mrlacey** [comment]
> @mrlacey Would it be possible to add a selection box and disable the two problematic options when choosing .NET5?

It would definitely be possible to have two options (3.1 Core or 5.0) but I question the benefit that this would bring based on the extra effort of maintaining the extra option.

What are the benefits of switching to 5.0? 

Other than it being newer, I'm not clear on the benefit of switching from 3.1 which has the benefit of Long Term Support.

**Comment by Luk164** [comment]
@mrlacey Many libraries I use have been updating to 5.0 and I merely thought it would be natural to move on. No other reason really. I even created a fresh WPF project and switched it to 5.0 myself to see if everything worked (no WebView or XAML Islands of course). I can work with this either way so it is not a huge problem for me.

**Comment by mrlacey** [comment]
Upon reflection, if and when updating to .NET5, I think it would be wise to also maintain support for 3.1 as that has LTS which is likely to be an important factor when making decisions about which frameworks and which versions of those frameworks to use.

**Comment by Luk164** [comment]
@mrlacey I would suggest passing the question around a bit to see some other ideas. Maybe mark this issue for discussion?

**Comment by sibille** [comment]
I agree with @mrlacey, think we should stay in .NET Core 3.1 as this is the current LTS version, and .NET 5 does not support XamlIsland and WebView. It's also what Visual Studio uses for the WPF project template.

**Comment by DocBrown101** [comment]
.NET 6 now has LTS status. Will there be a WPF template update?

**Comment by mikebattista** [comment]
We are evaluating the [.NET support lifecycle](https://github.com/dotnet/core/blob/main/releases.md#supported-net-versions) for how best to move forward with the templates.

.NET 6 seems like the logical next update here since everything older is going out of support this year.

**Comment by mrlacey** [comment]
X-Ref #4401

**Comment by mikebattista** [comment]
Merged with #4422. Will be part of our upcoming VS 2022 release.
