### ISSUE TITLE
Verify nuget packages and licences used in templates

### ISSUE THREAD

**Issue by sibille** [microsoft/TemplateStudio#4116]
We should add a step to template validation tests to validate the nuget packages we use on the templates are valid, available on nuget.org and licenses are correct.

**Comment by mrlacey** [comment]
If the packages aren't available won't lots of other generation tests fail? Do we need a separate check for this?

How will testing that "licenses are correct" work? What should be checked?

**Comment by sibille** [comment]
That's true, if packages are not available other generation tests would fail, but checking if the NuGet package is available on nuget.org is quicker. I think the license can also be checked against nuget.org.

**Comment by mrlacey** [comment]
> but checking if the NuGet package is available on nuget.org is quicker

Quicker how?
This will involve additional tests and therefore take more time. Yes, a new test for just this could be run in isolation but when and why would such a test be run in isolation?

> I think the license can also be checked against nuget.org.

Checked how?
What will be checked?

**Comment by mikebattista** [comment]
I don't see a need for an additional test here.

**Comment by mrlacey** [comment]
My previous pushback on this issue was due to the lack of detail and there being no justification for making the proposed changes.

Based on what I remember, there was a period of time when preview versions of some nuget packages were removed when new ones were made available. This caused project generation to fail because the required version of a package was unavailable.
Also, there was a time when many open-source projects renamed their "main" branches, and as many also kept their license files in their repositories, this led to possible 404s when following the links shown from the wizard UI.

We do actually already have tests for the license links and so no change is required there.
While I recognize that checking a (version of a) package exists on NuGet before trying to generate an app, the removal of a nuget package happens so rarely (under normal circumstances) that I don't think it justifies the need to create extra tests and it is sufficient to have this scenario covered by the generation tests.
Additional arguments against tests being run infrequently due to the amount of time they take should be addressed as part of other work to refactor tests and make them faster.
