### ISSUE TITLE
WindowsTemplateStudio and migration to WindowsAppSDK

### ISSUE THREAD

**Issue by myokeeh** [microsoft/TemplateStudio#4387]
I'm fairly reliant on Windows Template Studio for the UWP apps I make.

I'm trying to understand when WTS would be ready with WindowsAppSDK. I haven't tried any migration attempts, but feel the need to do it soon.

Is the migration guidance presented in the discussion below applicable to my current WTS UWP apps? Will it be compatible with WTS after that migration?

https://github.com/microsoft/WindowsAppSDK/discussions/1615

**Comment by Javier118** [comment]
How can i install WTS for Visual Studio 2022 ?

**Comment by mikebattista** [comment]
Visual Studio 2022 is not supported yet. It is on the [roadmap](https://github.com/microsoft/TemplateStudio/blob/dev/docs/roadmap.md), though, which we just updated.

**Comment by myokeeh** [comment]
What's the timeline like for Template Studio for WinUI (C#)?

**Comment by mikebattista** [comment]
We just shipped the 2022 extensions!

See https://github.com/microsoft/TemplateStudio/issues/4353#issuecomment-1112723860 for details.

I'm going to close out this issue since Template Studio for WinUI is updated for WinAppSDK 1.0.1 and will be updated to newer versions as they are released.

Regarding the original question about migrating a UWP project to WinUI/WinAppSDK, a couple things to note:

* Projects created with the 2019 extension won't be updateable with the 2022 extensions, even if you stay with UWP. They are different extensions with different IDs which is a requirement of VS 2022.
* The UWP extension has many more options than the WinUI extension given how new the WinUI extension is and how long the UWP extension has been around. If you heavily rely on all the features there, you might want to stick with UWP for now.

With the 2022 extensions out now, we'll be looking at rounding out the feature set in the WinUI extension relative to UWP, but that will take some time.
