### ISSUE TITLE
Replace "WindowsTemplateStudio" references with "TemplateStudio"

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4396]
Need to update ico filenames, template manifests, code comments, schema names, licenses, etc.

**Comment by mrlacey** [comment]
Note that needs to also include the common abbreviation of "WinTS" and the "Wts" and "wts" prefixes that are also used throughout the code.

`wts.` is also used as a prefix in the template tags. will this be changed too?

Also, "WTS" is used in the generated code to distinguish `TODO` comments that are created from the templates and those that are otherwise included. Should these be changed too? (So `TODO WTS:...` would become `TODO TS:...`)

**Comment by mikebattista** [comment]
Yes I want to replace all of that. I already updated comments and things in my template update branches and was waiting to refactor the template schema until you merge your work. I don't want to do that twice.

Finish what you need to so we can merge your refactor work then we can work on this together.

**Comment by mikebattista** [comment]
Remaining changes:

- [ ] _utils\code-snippets.json
- [ ] design\Assets\Logo
- [ ] code\SharedStyles\TemplateStudioStyles.xaml
- [ ] wts.* in all template.json files
- [ ] code\test\SharedFunctionality.Core.Tests\Composition\CompositionQueryTest.cs
- [ ] code\test\SharedFunctionality.Tests\TemplateValidator\TemplateJsonVerifier.cs
- [ ] code\test\SharedFunctionality.Tests\TemplateValidator\ValidationTemplateInfo.cs
- [ ] code\tools\TemplateValidator\TemplateJsonVerifier.cs
- [ ] code\tools\TemplateValidator\ValidationTemplateInfo.cscode\test\TemplateStudioForUWP.Tests\VB\TemplateJsonLanguageConsistencyTests.cs
- [ ] *.vstemplate

**Comment by mikebattista** [comment]
Majority of product changes merged with #4450.
