### ISSUE TITLE
"Package and Publish" > "Create App Packages..." Crashes Visual Studio

### ISSUE THREAD

**Issue by bennybroseph** [microsoft/TemplateStudio#4534]
### Describe the bug

Creating a brand new project using the template and attempting to package and publish it freezes and then crashes Visual Studio instead.

### To Reproduce

 1. Create a new project using the template studio
 2. Right click on the new project
 3. Click on "Package and Publish"
 4. Click on "Create App Packages"
 5. Visual Studio freezes
 6. Visual Studio crashes

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2.0 Preview 6.0
 - Template Studio Wizard Version: 5.1
 - Windows Build: 19044.1706

**Comment by mikebattista** [comment]
This was a known issue that was fixed in 17.2.2 or .3. If you update your VS install, the issue should be resolved.

**Comment by bennybroseph** [comment]
I'm getting the same issue after updating. Is there anything else that should be changed that the old version may have set?

**Comment by bennybroseph** [comment]
Actually, it's not just the previous project that was created on 17.2.0 Preview 6.0. It's completely new ones as well.

**Comment by mikebattista** [comment]
The bug was an interaction between WinAppSDK 1.1 and Visual Studio with the fix being in Visual Studio itself. Can you downgrade the WinAppSDK NuGet package reference in the project to 1.0.x and see if it still reproes? If it doesn't repro with 1.0 and does repro with 1.1, then it's likely the same known issue which latest builds of VS should not have.

If it's the same issue, and after updating VS to the latest stable 17.2 build and rebooting and everything it still reproes, then I'd recommend [Reporting a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) and recording the repro. I'm on 17.2.3 and can't repro.

**Comment by bennybroseph** [comment]
So reverting to the non-preview version worked. The latest preview version is still bugged though. I attempted it on two PCs and ran into the same issue on preview and resolved it by reverting to the non-preview

**Comment by mikebattista** [comment]
Thanks for confirming. I just checked with VS and the fix for the bug is making its way into the preview releases. It will be fixed in 17.3 Preview 2 coming out next week.
